# Generated by Django 3.1.7 on 2021-03-01 10:07

import account.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverPictureModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Cover Picture')),
                ('hash', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('path', models.ImageField(upload_to=account.models.file_path, verbose_name='picture')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cover Photo',
                'ordering': ['date_posted'],
            },
        ),
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='audio new name')),
                ('hash', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True)),
                ('audio', models.FileField(upload_to=account.models.file_path, verbose_name='audio')),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audio',
                'ordering': ['date_posted'],
            },
        ),
    ]
