# Generated by Django 2.1.5 on 2019-06-27 08:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash',
            field=models.UUIDField(default=uuid.UUID('cd847e6f-4ef1-4135-ab0a-d7f6fbe392c7'), editable=False, unique=True, verbose_name='User Key'),
        ),
        migrations.AlterField(
            model_name='user',
            name='block',
            field=models.BooleanField(default=False, verbose_name='activate'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
    ]
